name: Update helm repo
on:
  push:
    branches:
      - develop

jobs:
  package:
    name: Update helm repo
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package helm chart
      working-directory: docker/helm
      run: helm package . --destination /tmp/output

    - name: Switch to gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Copy packaged file
      run: cp /tmp/output/* helm/

    - name: Reindex helm repository
      working-directory: helm
      run: helm repo index .

    - uses: fregante/setup-git-user@v1

    - run: git add helm

    - run: git commit -m "Update helm chart"

    - run: git push origin gh-pages
